import { SCREEN_IDS } from '../../constants/routes'

export const AUTH_SCREENS = Object.freeze([
  SCREEN_IDS.SIGN_IN,
  SCREEN_IDS.SIGN_UP,
])

export const MAIN_TAB_SCREENS = Object.freeze([
  SCREEN_IDS.DASHBOARD,
  SCREEN_IDS.ORDERS,
  SCREEN_IDS.SLOTS,
  SCREEN_IDS.MONEY,
  SCREEN_IDS.MESSAGES,
  SCREEN_IDS.PROFILE,
])

export const PROFILE_STACK_SCREENS = Object.freeze([
  SCREEN_IDS.PROFILE_STATUS,
  SCREEN_IDS.PROFILE_TRANSPORT,
  SCREEN_IDS.PROFILE_IDENTITY,
  SCREEN_IDS.PROFILE_PARK_ACCESS,
  SCREEN_IDS.PROFILE_PAYOUT_ACCOUNT,
  SCREEN_IDS.PROFILE_PAYOUT_HISTORY,
  SCREEN_IDS.PROFILE_NOTIFICATIONS,
  SCREEN_IDS.PROFILE_LANGUAGE,
])
