import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f3e9dc',
  },
  scrollArea: {
    flex: 1,
    backgroundColor: '#f3e9dc',
  },
  content: {
    flexGrow: 1,
    backgroundColor: '#ffffff',
  },
  hero: {
    backgroundColor: '#f3e9dc',
  },
  heroImage: {
    opacity: 0.42,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(243, 233, 220, 0.50)',
  },
  header: {
    height: 104,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#444040',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '800',
  },
  headerSpacer: {
    width: 44,
    height: 44,
  },
  profilePanel: {
    flex: 1,
    minHeight: 560,
    marginTop: -34,
    paddingTop: 0,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  avatar: {
    borderWidth: 4,
    borderColor: '#ffffff',
    backgroundColor: '#f2f4f6',
  },
  identity: {
    alignItems: 'center',
    marginTop: 18,
    gap: 6,
  },
  name: {
    color: '#000000',
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '900',
  },
  editProfile: {
    maxWidth: 240,
    color: '#a38e90',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  menuList: {
    alignSelf: 'stretch',
    marginTop: 36,
    gap: 4,
  },
  menuItem: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuText: {
    color: '#000000',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
  },
  logoutButton: {
    alignSelf: 'stretch',
    height: 52,
    marginTop: 88,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff7a59',
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
  },
  editOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
  },
  paymentOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#f7f9fb',
  },
  editScreen: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  editHeader: {
    height: 88,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  editBackButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editTitle: {
    color: '#000000',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '900',
  },
  editHeaderSpacer: {
    width: 44,
    height: 44,
  },
  editProfileBlock: {
    alignItems: 'center',
    paddingTop: 44,
  },
  editAvatar: {
    backgroundColor: '#f2f4f6',
  },
  editName: {
    marginTop: 20,
    color: '#000000',
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '900',
  },
  changePicture: {
    marginTop: 4,
    color: '#a38e90',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '900',
  },
  editRows: {
    marginTop: 58,
    gap: 3,
  },
  infoRow: {
    height: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
  },
  infoLabel: {
    color: '#000000',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
  },
  infoValueWrap: {
    flex: 1,
    maxWidth: 210,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 14,
  },
  infoValue: {
    flexShrink: 1,
    color: '#b5b5b5',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '900',
    textAlign: 'right',
  },
  saveArea: {
    marginTop: 'auto',
  },
  saveButton: {
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff7a59',
  },
  saveText: {
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
  },
  nameScreen: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  nameHeader: {
    height: 88,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nameHeaderTitle: {
    color: '#000000',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '900',
  },
  nameContent: {
    paddingHorizontal: 14,
    paddingTop: 28,
    paddingBottom: 28,
  },
  nameVerificationTitle: {
    color: '#000000',
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '900',
    textAlign: 'center',
  },
  nameForm: {
    marginTop: 28,
    gap: 14,
  },
  emailContent: {
    paddingHorizontal: 14,
    paddingTop: 28,
    paddingBottom: 28,
  },
  emailForm: {
    marginTop: 56,
    gap: 4,
  },
  nameFieldGroup: {
    gap: 4,
  },
  nameFieldLabel: {
    color: '#111827',
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '800',
  },
  nameInput: {
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#b5b5b5',
    backgroundColor: '#e6e8ea',
    color: 'rgba(0, 0, 0, 0.65)',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  signatureWrap: {
    height: 300,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 70,
    transform: [{ translateX: 8 }],
  },
  nameSaveArea: {
    paddingHorizontal: 46,
    backgroundColor: '#ffffff',
  },
  nameSaveButton: {
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff7a59',
  },
  nameSaveText: {
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
  },
  emailIllustrationWrap: {
    height: 308,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 125,
  },
  emailIllustration: {
    width: 300,
    height: 250,
  },
  phoneContent: {
    paddingHorizontal: 38,
    paddingTop: 28,
    paddingBottom: 28,
  },
  phoneForm: {
    marginTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  countryInputWrap: {
    width: 58,
    height: 42,
    paddingLeft: 5,
    paddingRight: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#b5b5b5',
    backgroundColor: '#e6e8ea',
    flexDirection: 'row',
    alignItems: 'center',
  },
  flagCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#66c7bf',
  },
  flagText: {
    color: '#f5df53',
    fontSize: 7,
    lineHeight: 9,
    fontWeight: '900',
  },
  countryInput: {
    flex: 1,
    height: 40,
    padding: 0,
    color: 'rgba(0, 0, 0, 0.55)',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    textAlign: 'center',
  },
  phoneInput: {
    flex: 1,
    maxWidth: 204,
    height: 42,
    paddingHorizontal: 14,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#b5b5b5',
    backgroundColor: '#e6e8ea',
    color: 'rgba(0, 0, 0, 0.55)',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    textAlign: 'center',
  },
  phoneIllustrationWrap: {
    height: 350,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 70,
  },
  phoneIllustration: {
    width: 286,
    height: 334,
  },
  passwordContent: {
    paddingHorizontal: 14,
    paddingTop: 28,
    paddingBottom: 28,
  },
  passwordForm: {
    marginTop: 30,
    gap: 14,
  },
  passwordInput: {
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#b5b5b5',
    backgroundColor: '#ffffff',
    color: 'rgba(0, 0, 0, 0.65)',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  passwordIllustrationWrap: {
    height: 388,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
  },
  paymentScreen: {
    flex: 1,
    backgroundColor: '#f7f9fb',
  },
  paymentHeader: {
    height: 64,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(247, 249, 251, 0.90)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentHeaderTitle: {
    color: '#191c1e',
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '800',
  },
  paymentHeaderSpacer: {
    width: 40,
    height: 40,
  },
  paymentContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  paymentSectionLabel: {
    color: '#58423c',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  paymentMethodsRow: {
    marginTop: 24,
    flexDirection: 'row',
    gap: 14,
  },
  paymentMethodCard: {
    width: 100,
    height: 110,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: '#191c1e',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  paymentMethodText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  savedCardsSection: {
    marginTop: 38,
  },
  savedCardsTitle: {
    color: '#191c1e',
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '800',
  },
  savedCardsList: {
    marginTop: 16,
    gap: 16,
  },
  savedCard: {
    minHeight: 88,
    padding: 20,
    borderRadius: 32,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    borderWidth: 1,
    borderColor: 'rgba(223, 192, 184, 0.15)',
    overflow: 'hidden',
  },
  savedCardSelected: {
    backgroundColor: '#ffdad2',
    borderColor: 'rgba(167, 57, 30, 0.10)',
  },
  savedCardBrand: {
    width: 48,
    height: 32,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f2f4f6',
  },
  savedCardBrandSelected: {
    backgroundColor: '#ffffff',
  },
  savedCardVisaText: {
    color: '#1e5bba',
    fontSize: 12,
    lineHeight: 16,
    fontStyle: 'italic',
    fontWeight: '900',
  },
  mastercardMark: {
    width: 28,
    height: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  mastercardCircleRed: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(235, 0, 27, 0.80)',
  },
  mastercardCircleOrange: {
    width: 16,
    height: 16,
    marginLeft: -8,
    borderRadius: 8,
    backgroundColor: 'rgba(247, 158, 27, 0.80)',
  },
  savedCardBody: {
    flex: 1,
    gap: 4,
  },
  savedCardNumber: {
    color: '#191c1e',
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '700',
    letterSpacing: 0.9,
  },
  savedCardNumberSelected: {
    color: '#701500',
    fontWeight: '800',
  },
  savedCardLabel: {
    color: '#58423c',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    letterSpacing: 0.6,
  },
  savedCardLabelSelected: {
    color: '#3c0700',
    fontWeight: '700',
  },
  savedCardRadio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e6e8ea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  savedCardRadioSelected: {
    borderWidth: 0,
    backgroundColor: '#a7391e',
  },
  savedCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  savedCardDeleteButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
  },
  addNewCardButton: {
    height: 56,
    marginTop: 16,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(223, 192, 184, 0.50)',
    backgroundColor: '#f2f4f6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  addNewCardText: {
    color: '#a7391e',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '800',
  },
  paymentEmptyState: {
    alignItems: 'center',
    marginTop: 58,
  },
  paymentIllustrationWrap: {
    height: 260,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentEmptyTitle: {
    marginTop: 16,
    color: '#191c1e',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    textAlign: 'center',
  },
  paymentEmptySubtitle: {
    marginTop: 8,
    color: '#58423c',
    fontSize: 16,
    lineHeight: 25.6,
    fontWeight: '400',
    textAlign: 'center',
  },
  paymentBottomAction: {
    paddingHorizontal: 24,
    backgroundColor: '#f7f9fb',
  },
  paymentAddButton: {
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff7a59',
    shadowColor: '#a7391e',
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  paymentAddButtonText: {
    color: '#701500',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '800',
  },
  addPaymentContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  cardPreview: {
    minHeight: 194,
    paddingHorizontal: 32,
    paddingTop: 32,
    paddingBottom: 18,
    borderRadius: 32,
    overflow: 'hidden',
    backgroundColor: '#ff7a59',
    shadowColor: '#a7391e',
    shadowOpacity: 0.15,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 16 },
    elevation: 4,
  },
  cardGlow: {
    position: 'absolute',
    width: 256,
    height: 256,
    right: -90,
    top: -80,
    borderRadius: 128,
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  cardChip: {
    width: 48,
    height: 40,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.20)',
  },
  cardChipInner: {
    width: 32,
    height: 24,
    borderRadius: 2,
    backgroundColor: 'rgba(251, 191, 36, 0.80)',
  },
  cardBrand: {
    width: 52,
    height: 32,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardBrandCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.20)',
  },
  cardBrandOverlap: {
    marginLeft: -12,
    backgroundColor: 'rgba(255, 255, 255, 0.30)',
  },
  cardPreviewBody: {
    marginTop: 28,
    gap: 16,
  },
  cardPreviewLabel: {
    color: 'rgba(255, 255, 255, 0.70)',
    fontSize: 10,
    lineHeight: 15,
    fontWeight: '500',
    letterSpacing: 1,
  },
  cardPreviewNumber: {
    marginTop: 4,
    color: '#ffffff',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '800',
    letterSpacing: 4,
  },
  cardPreviewBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardPreviewValue: {
    marginTop: 4,
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    letterSpacing: 0.35,
  },
  cardPreviewRightText: {
    textAlign: 'right',
  },
  addPaymentForm: {
    marginTop: 40,
    gap: 24,
  },
  addPaymentField: {
    gap: 8,
  },
  addPaymentLabel: {
    paddingLeft: 16,
    color: '#8b716b',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  addPaymentInputWrap: {
    height: 64,
    borderRadius: 6,
    backgroundColor: '#e6e8ea',
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  addPaymentInput: {
    flex: 1,
    height: 64,
    paddingHorizontal: 24,
    color: '#58423c',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400',
  },
  addPaymentInputIcon: {
    width: 48,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPaymentTwoColumn: {
    flexDirection: 'row',
    gap: 16,
  },
  addPaymentHalfField: {
    flex: 1,
  },
  addPaymentCenteredInput: {
    textAlign: 'center',
  },
  saveCardRow: {
    paddingTop: 16,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  saveCardCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff7a59',
  },
  saveCardCheckInactive: {
    backgroundColor: '#e6e8ea',
  },
  saveCardText: {
    color: '#8b716b',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
})
